package com.sanjay900.jgbe.emu;
/*
 *  IMPORTANT: THIS FILE IS AUTOGENERATED
 *
 *  Any modifications to this file will be lost when regenerating it.
 *  Modify the corresponding .jpp file instead, and regenerate this file.
 */




import java.io.*;





public class DirectByteArrayOutputStream
                       extends ByteArrayOutputStream {



    public DirectByteArrayOutputStream(){
        super();
    }



    public DirectByteArrayOutputStream( int size ){
        super( size );
    }





    public synchronized byte[] getByteArray(){
        return buf;
    }




    public synchronized byte[] swap( byte[] newBuf ){
        byte[] oldBuf = buf;
        buf = newBuf;
        reset();
        return oldBuf;
    }
}
