name: Gameboy
version: 1.0 Release
main: com.sanjay900.jgbe.bukkit.GameboyPlugin
depend: [ProtocolLib]
api-version: "1.15"
commands:
    gameboy:
        aliases: [gb, game, gba]
        description: Gameboy related commands.
        usage: /gameboy